# Based on:
# https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action
# https://github.com/marketplace/actions/build-and-push-docker-images
# https://docs.docker.com/build/ci/github-actions/multi-platform/
# https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
# https://docs.docker.com/build/ci/github-actions/cache/
# https://docs.docker.com/build/ci/github-actions/attestations/
# https://docs.docker.com/build/ci/github-actions/reproducible-builds/

# TODO:
# - Push to openregistry.dev
# - Test before push seems like a nice thing to have
# - are attestations and sbom working?

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.output.outputs.image_tag }}
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    steps:
      # Log into hub.docker.com to avoid unauthenticated rate limting
      # https://docs.docker.com/docker-hub/usage/
      # - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - id: output
        run: echo "image_tag=$(git branch --show-current)-$(git rev-parse --short=7 HEAD)-$(git log -1 --pretty=%ct)" >> $GITHUB_OUTPUT
      - uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

          # dev-{{sha}}-{{commit_date 'X'}} was added for Flux. See https://fluxcd.io/flux/guides/image-update/#imagepolicy-examples
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long
            type=raw,value=${{ steps.output.outputs.image_tag }}

      - uses: docker/setup-docker-action@e61617a16c407a86262fb923c35a616ddbe070b3 # v4.6.0
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Get Git commit timestamps for reproducible builds
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
        with:
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64,linux/arm64
          provenance: mode=max
          push: ${{ github.event_name != 'pull_request' }}
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          # build-args: |
          #   POETRY_HTTP_BASIC_GITLAB_USERNAME=${{ env.POETRY_HTTP_BASIC_GITLAB_USERNAME }}
          # secrets: |
          #   POETRY_HTTP_BASIC_GITLAB_PASSWORD=${{ secrets.POETRY_HTTP_BASIC_GITLAB_PASSWORD }}
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
      #   with:
      #     push-to-registry: true
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      # - uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      #   with:
      #     image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}'
      #     format: 'table'
      #     exit-code: '1'
      #     ignore-unfixed: true
      #     vuln-type: 'os,library'
      #     severity: 'CRITICAL,HIGH'
